### ISSUE TITLE
Tracking Issue for Milestone 3

### ISSUE THREAD

**Issue by scilio** [mimblewimble/mwixnet#11]
- [x] https://github.com/mimblewimble/mwixnet/issues/6
- [x] https://github.com/mimblewimble/mwixnet/issues/14
- [x] https://github.com/mimblewimble/mwixnet/issues/13
- [x] https://github.com/mimblewimble/mwixnet/issues/5
- [ ] https://github.com/mimblewimble/mwixnet/issues/4
- [ ] https://github.com/mimblewimble/mwixnet/issues/8
- [x] https://github.com/mimblewimble/mwixnet/issues/9
- [x] https://github.com/mimblewimble/mwixnet/issues/10
- [x] https://github.com/mimblewimble/mwixnet/issues/19
